#! /bin/sh
#██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
# Bspwm configuration file:

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width            3
bspc config window_gap              12
bspc config bottom_padding          5

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config single_monocle 	        true
bspc config ignore_ewmh_focus	    true

bspc config focused_border_color    "#ffc1c6"
bspc config normal_border_color     "#6c6364"

# Custom rules:
bspc rule -a LibreWolf desktop='^2' state=tiled follow=on
bspc rule -a Brave-browser desktop='^2' state=tiled follow=on
bspc rule -a discord desktop='^3' state=tiled follow=on
bspc rule -a Steam desktop='^4' state=tiled follow=on
bspc rule -a Spotify desktop='^5' state=tiled follow=on

bspc rule -a steam_app_1050280 desktop='^4' state=tiled follow=on

$HOME/.config/polybar/launch.sh
